connect odi_user/welcome1@localhost:1521/ORCLPDB
SET LINESIZE 120
COLUMN AD_SOYAD FORMAT A25
COLUMN DEPARTMAN_ADI FORMAT A25
COLUMN MAAS_SEVIYE FORMAT A12

SELECT * FROM CALISAN_RAPOR ORDER BY CALISAN_ID;

SELECT 'Toplam: ' || COUNT(*) || ' kayit yuklendi' AS SONUC FROM CALISAN_RAPOR;

exit;
