-- Proje 2: Cok Tablolu ETL - Tablo Olusturma
-- Kullanim: sqlplus odi_user/welcome1@localhost:1521/ORCLPDB @create_tables.sql

-- Onceki tablolari temizle (varsa)
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE CALISAN_RAPOR';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE CALISANLAR2';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE DEPARTMANLAR';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- DEPARTMANLAR tablosu (kaynak)
CREATE TABLE DEPARTMANLAR (
    DEPARTMAN_ID   NUMBER(10) PRIMARY KEY,
    DEPARTMAN_ADI  VARCHAR2(50),
    LOKASYON       VARCHAR2(50)
);

-- CALISANLAR2 tablosu (kaynak - yeni versiyon)
CREATE TABLE CALISANLAR2 (
    CALISAN_ID    NUMBER(10) PRIMARY KEY,
    AD            VARCHAR2(50),
    SOYAD         VARCHAR2(50),
    DEPARTMAN_ID  NUMBER(10),
    MAAS          NUMBER(10,2),
    CONSTRAINT FK_DEPT FOREIGN KEY (DEPARTMAN_ID) REFERENCES DEPARTMANLAR(DEPARTMAN_ID)
);

-- CALISAN_RAPOR tablosu (hedef)
CREATE TABLE CALISAN_RAPOR (
    CALISAN_ID     NUMBER(10) PRIMARY KEY,
    AD_SOYAD       VARCHAR2(100),
    DEPARTMAN_ADI  VARCHAR2(50),
    MAAS           NUMBER(10,2),
    MAAS_SEVIYE    VARCHAR2(20)
);

-- Departman verileri
INSERT INTO DEPARTMANLAR VALUES (1, 'Bilgi Teknolojileri', 'Istanbul');
INSERT INTO DEPARTMANLAR VALUES (2, 'Insan Kaynaklari', 'Ankara');
INSERT INTO DEPARTMANLAR VALUES (3, 'Muhasebe', 'Istanbul');
INSERT INTO DEPARTMANLAR VALUES (4, 'Pazarlama', 'Izmir');
INSERT INTO DEPARTMANLAR VALUES (5, 'Uretim', 'Bursa');

-- Calisan verileri (20 kayit - farkli maas araliklari)
INSERT INTO CALISANLAR2 VALUES (101, 'Ahmet', 'Yilmaz', 1, 12000);
INSERT INTO CALISANLAR2 VALUES (102, 'Mehmet', 'Kaya', 1, 15000);
INSERT INTO CALISANLAR2 VALUES (103, 'Ayse', 'Demir', 2, 9000);
INSERT INTO CALISANLAR2 VALUES (104, 'Fatma', 'Celik', 2, 4500);
INSERT INTO CALISANLAR2 VALUES (105, 'Ali', 'Ozturk', 3, 8000);
INSERT INTO CALISANLAR2 VALUES (106, 'Zeynep', 'Arslan', 3, 11000);
INSERT INTO CALISANLAR2 VALUES (107, 'Mustafa', 'Sahin', 4, 7500);
INSERT INTO CALISANLAR2 VALUES (108, 'Elif', 'Dogan', 4, 3500);
INSERT INTO CALISANLAR2 VALUES (109, 'Hasan', 'Kilic', 5, 6000);
INSERT INTO CALISANLAR2 VALUES (110, 'Huseyin', 'Acar', 5, 4000);
INSERT INTO CALISANLAR2 VALUES (111, 'Emre', 'Yildiz', 1, 18000);
INSERT INTO CALISANLAR2 VALUES (112, 'Selin', 'Aydin', 2, 7000);
INSERT INTO CALISANLAR2 VALUES (113, 'Burak', 'Ozdemir', 3, 5500);
INSERT INTO CALISANLAR2 VALUES (114, 'Deniz', 'Erdogan', 4, 9500);
INSERT INTO CALISANLAR2 VALUES (115, 'Canan', 'Kurt', 5, 5000);
INSERT INTO CALISANLAR2 VALUES (116, 'Kerem', 'Ozkan', 1, 22000);
INSERT INTO CALISANLAR2 VALUES (117, 'Merve', 'Simsek', 2, 6500);
INSERT INTO CALISANLAR2 VALUES (118, 'Onur', 'Yalcin', 3, 13000);
INSERT INTO CALISANLAR2 VALUES (119, 'Pinar', 'Koc', 4, 8500);
INSERT INTO CALISANLAR2 VALUES (120, 'Serkan', 'Tas', 5, 3000);

COMMIT;

-- Dogrulama
SELECT 'DEPARTMANLAR: ' || COUNT(*) || ' kayit' AS sonuc FROM DEPARTMANLAR
UNION ALL
SELECT 'CALISANLAR2:  ' || COUNT(*) || ' kayit' FROM CALISANLAR2
UNION ALL
SELECT 'CALISAN_RAPOR: ' || COUNT(*) || ' kayit (bos olmali)' FROM CALISAN_RAPOR;

EXIT;
